### ISSUE TITLE
shortcuts.vdf does not exist

### ISSUE THREAD

**Issue by kode54** [ticky/lnshot#3]
My Steam config folder does not contain a config/shortcuts.vdf, so this tool fails at that step. Do I need to instruct Steam to create shortcuts for every game when I install them for this to exist?

**Comment by ticky** [comment]
Ah, that's an oversight on my part; my code presumes you've added at least one non-steam game shortcut to your Steam library, I'll look at removing that requirement.

**Comment by ticky** [comment]
I've just pushed fefa8e504e03317bf5cf1b2a6b2c0977f4ca3fd6 to my `daemon` branch, which should ignore this error. Let me know how it goes!
